### ISSUE TITLE
got a running error

### ISSUE THREAD

**Issue by jcl2023** [botextractai/ai-crewai-multi-agent#1]
when I run python3 ./main.py
I encountered an error while trying to use the tool. This was the error: SECTools.search_10k() got an unexpected keyword argument 'MSFT'.
 Tool Search 10-K form accepts these inputs: Search 10-K form(data) - Useful to search information from the latest 10-K form for a
given stock.
The input to this tool should be a pipe (|) separated text of
length two, representing the stock ticker you are interested, what
question you have from it.
For example, `MSFT|what was last year's revenue`.

Any idea what goes wrong?

**Comment by botextractai** [comment]
Hi [cl2023](https://github.com/jcl2023)

I assume that you have cloned the repo with:
`git clone https://github.com/botextractai/ai-crewai-multi-agent.git`

I further assume that you have then installed all requirements with:
`pip install -r requirements.txt`
(or in a virtual environment using Anaconda, Poetry, etc.)

This should also create the bytecode files in the `__pycache__` folders. I have just tested it on Microsoft Windows, but this might be an issue in some operating systems.

I have just done that, and it worked for me. The question is what kind of error message that you got just after the text that you have quoted. The text that you have quoted is the tool description from `./tools/sec_tools.py` .

If you run the script in Visual Studio Code, then your text (the tool description) will appear in green and a possible error message in red just blow that. I need to know this exact error message.

If you got this error message

`I encountered an error while trying to use the tool. This was the error: API error: 403 - {"status":403,"error":"API token invalid. Please get a valid token from sec-api.io"}.`

then it means that you need to replace the API key in the `main.py` file with a valid key from https://sec-api.io/login .
